### PR TITLE
Create CI for tup

### PR DESCRIPTION
**Pull request by petemoore**
A simple CI running in github actions.

Not 100% ready yet - so I'd appreciate any help with the remaining issues (below). Initially I've set it up for Windows/macOS/Linux. I haven't looked into FreeBSD/NetBSD/SunOS yet, as I didn't want to get ahead of myself 😝.

### Ubuntu

One failure:

```
2021-08-10T12:53:20.6771960Z [36m --- Run t4047-open-fds.sh --- [0m
2021-08-10T12:53:20.6860066Z .tup repository initialized: .tup/db
2021-08-10T12:53:20.6915203Z [ tup ] [0.000s] Scanning filesystem...
2021-08-10T12:53:20.6917627Z [ tup ] [0.000s] Reading in new environment variables...
2021-08-10T12:53:20.6919805Z [ tup ] [0.001s] Parsing Tupfiles...
2021-08-10T12:53:20.6968430Z  100% 0) [0.001s] .
2021-08-10T12:53:20.6985500Z [ tup ] [0.007s] No files to delete.
2021-08-10T12:53:20.6986516Z [ tup ] [0.007s] Generating .gitignore files...
2021-08-10T12:53:20.6987327Z [ tup ] [0.007s] Executing Commands...
2021-08-10T12:53:20.7028322Z  100% 0) [0.004s] ls -l /proc/$$/fd > fds.txt
2021-08-10T12:53:20.7032173Z [ tup ] [0.012s] Updated.
2021-08-10T12:53:20.7198334Z Error: These fds shouldn't be open: total 0
2021-08-10T12:53:20.7199534Z lr-x------ 1 runner docker 64 Aug 10 12:53 106 -> pipe:[31451]
2021-08-10T12:53:20.7200594Z l-wx------ 1 runner docker 64 Aug 10 12:53 109 -> pipe:[31452]
2021-08-10T12:53:20.7201647Z lrwx------ 1 runner docker 64 Aug 10 12:53 11 -> socket:[30698]
2021-08-10T12:53:20.7202661Z lrwx------ 1 runner docker 64 Aug 10 12:53 14 -> socket:[31753]
2021-08-10T12:53:20.7203946Z lr-x------ 1 runner docker 64 Aug 10 12:53 45 -> /dev/urandom
2021-08-10T12:53:20.7205045Z lr-x------ 1 runner docker 64 Aug 10 12:53 47 -> /dev/urandom
2021-08-10T12:53:20.7206077Z lrwx------ 1 runner docker 64 Aug 10 12:53 8 -> socket:[23771]
```

### macOS

No failures!

### Windows

I'm not sure which shell environment I should be using on Windows, so in this version I set up MSYS2 (MINGW64). However, the build complains that fuse3 is required, and that may be because I'm using the wrong shell, or maybe because fuse3 is really required. Any advice here appreciated. Thanks!

```
Package fuse was not found in the pkg-config search path.
```

Not sure if this PR will link to the test results, or if you'll only see them after merging, so they are [here](https://github.com/petemoore/tup/actions/runs/1116663845) if you want to see them.

### CODE REVIEW

**Comment by gittup** [comment]
Awesome work!

For the open-fds test that is failing on Ubuntu, I wonder if it would help to change it to do something like:

```
cat > Tupfile << HERE
: |> ls -l /proc/\$\$/fd > %o |> fds.txt
HERE
update

ls -l /proc/self/fd > .tup/orig-fds.txt

diff .tup/orig-fds.txt fds.txt | grep '^>' | [ignore stdin /dev/null, stdout and such here]
```

The test is just trying to make sure that tup isn't leaving any open file descriptors around that aren't closed-on-exec and potentially messing with the subprocesses. (I've run into one or two tools that are negatively impacted if say, fd 3 is open when they don't expect it to be). Doing it with a diff like above can compare the open fds from the build environment with the open fds in the tup subprocess, and see if there are any extras. There will be some differences, since we close stdin and redirect stdout/stderr to files. But hopefully the diff would get rid of things like an extra pipe opened by the build env.

For Windows, build.sh unfortunately isn't supported there. To test local Windows builds, I just build with an already-built tup.exe, so that may present a chicken-and-egg problem. I think there are a few options here:

1) Update build.sh to support Windows
2) Download a published Windows build and use it to build the test version (from http://gittup.org/tup/win32/tup-latest.zip)
3) Cross-compile a new Windows binary from an Ubuntu instance with a tup.config:

```
CONFIG_CC=x86_64-w64-mingw32-gcc
CONFIG_CC32=i686-w64-mingw32-gcc
CONFIG_TARGET=win32
```

The first option probably makes the most sense?

**Comment by gittup** [comment]
Also, is it practical to run the tests through valgrind/helgrind? In my local CI, I test every commit on a bunch of platforms, and if they all pass then I test the latest commit again on Linux distros with TUP_VALGRIND=1 or TUP_HELGRIND=1 in the environment, which runs tup in the test cases with those checkers. (The environment variables are used in test/tup.sh, for reference).

The tests take a long time to run with these on, which is why I don't test every commit with them, but I have found them very useful for finding various issues.

**Comment by petemoore** [comment]
I've commented out the windows build/test github action for when build.sh supports Windows. I'm happy to work on that in a separate PR. I've amended the `t4047-open-fds.sh` test to keep a record of open file descriptors, before running tup, while running tup, and after running tup. If before and after differ, except for file descriptors 1 and 3, then the test will fail, and report the open file descriptors in all three stages (before running tup, while running tup, after running tup).

This doesn't exactly match your suggestion, but is it still ok?

I had a quick look to see if I could find a way of running the tests also on gentoo and fedora, but didn't immediately discover a simple solution for that.

Regarding valgrind/helgrind - I'm happy to look at that in a separate PR if that is ok?

**Comment by gittup** [comment]
> I've commented out the windows build/test github action for when build.sh supports Windows. I'm happy to work on that in a separate PR. I've amended the `t4047-open-fds.sh` test to keep a record of open file descriptors, before running tup, while running tup, and after running tup. If before and after differ, except for file descriptors 1 and 3, then the test will fail, and report the open file descriptors in all three stages (before running tup, while running tup, after running tup).

The before & after lists should always be identical - tup isn't able to open any file descriptors that stay open in the parent process (the shell running t4047). What I meant was to compare the list from the shell with the list generated while inside tup. Basically it's just a check that no unexpected fds are passed to the subprocesses. For example, tup has a handle for the SQLite db, and we don't want to leave it open for the child process.

The current iteration didn't take into account extra fds opened outside of the test case's control, though. So you could make the test fail by opening another file descriptor before running it. Eg:

```
$ cat fail.sh
exec 3< /etc/resolv.conf
./test.sh t4047-open-fds.sh
```

By comparing the generated fds with those already opened in the shell, we can prune out things like the extra pipes (or /etc/resolv.conf in this example).

I took a stab at updating the test myself, but haven't yet tested if it works with the CI patch. I merged the CI patch for now though so we can continue to iterate on it.

> I had a quick look to see if I could find a way of running the tests also on gentoo and fedora, but didn't immediately discover a simple solution for that.

Ahh ok. Locally I test on Ubuntu, Arch, and Fedora. There are frequently some small differences in the shell or libc/compiler versions that crop up and show failures. I don't know how useful that would be in a CI setup here though.

> Regarding valgrind/helgrind - I'm happy to look at that in a separate PR if that is ok?

Yeah, makes sense! Happy to be making progress here.

**Comment by gittup** [comment]
Ahh, I was treating the string as a regex, which didn't work well with the brackets in the pipe fd. Fix incoming!

**Comment by gittup** [comment]
Current run is green on Ubuntu & Macos! Nice work.

**Comment by petemoore** [comment]
Thanks for fixing @gittup !

**Comment by gittup** [comment]
@petemoore FYI I tried adding a build-win32.sh to the tree in case you want to give that a shot. It's created by running 'tup generate' in the tup repo, so it should be accurate compared to how it is built with tup itself. Unfortunately there are some bugs when trying to generate a .bat version, so if a bourne environment isn't supported in the GitHub CI, we may need to address that first.

**Comment by petemoore** [comment]
@gittup Thanks Mike! I had a quick stab, but wasn't successful first time (bizarelly the mingw gcc didn't seem to be installed, or couldn't be found, or was named differently to `x86_64-w64-mingw32-gcc`), but I'll see if I can get to the bottom of it when I have a bit more time. Thanks for creating the `build-win32.sh` script!

**Pull request closed without merging**
