### PR TITLE
Add NetBSD support

### PR DESCRIPTION
**Pull request by krytarowski**
I'm attaching patch adding preliminary support for NetBSD.

Our fuse implementation differs from Linux and FreeBSD and there are still some issues to be fixed. Besides the rest seems fine for now.

Build log.

```
$ sudo LD_LIBRARY_PATH=/usr/pkg/lib ./bootstrap.sh  
  mkdir build
  cd build
  bootstrap CC -g ../src/lua/lapi.c
  bootstrap CC -g ../src/lua/lauxlib.c
  bootstrap CC -g ../src/lua/lbaselib.c
  bootstrap CC -g ../src/lua/lbitlib.c
  bootstrap CC -g ../src/lua/lcode.c
  bootstrap CC -g ../src/lua/lcorolib.c
  bootstrap CC -g ../src/lua/lctype.c
  bootstrap CC -g ../src/lua/ldblib.c
  bootstrap CC -g ../src/lua/ldebug.c
  bootstrap CC -g ../src/lua/ldo.c
  bootstrap CC -g ../src/lua/ldump.c
  bootstrap CC -g ../src/lua/lfunc.c
  bootstrap CC -g ../src/lua/lgc.c
  bootstrap CC -g ../src/lua/linit.c
  bootstrap CC -g ../src/lua/liolib.c
  bootstrap CC -g ../src/lua/llex.c
  bootstrap CC -g ../src/lua/lmathlib.c
  bootstrap CC -g ../src/lua/lmem.c
  bootstrap CC -g ../src/lua/loadlib.c
  bootstrap CC -g ../src/lua/lobject.c
  bootstrap CC -g ../src/lua/lopcodes.c
  bootstrap CC -g ../src/lua/loslib.c
  bootstrap CC -g ../src/lua/lparser.c
  bootstrap CC -g ../src/lua/lstate.c
  bootstrap CC -g ../src/lua/lstring.c
  bootstrap CC -g ../src/lua/lstrlib.c
  bootstrap CC -g ../src/lua/ltable.c
  bootstrap CC -g ../src/lua/ltablib.c
  bootstrap CC -g ../src/lua/ltm.c
  bootstrap CC -g ../src/lua/lua.c
  bootstrap CC -g ../src/lua/luac.c
  bootstrap CC -g ../src/lua/lundump.c
  bootstrap CC -g ../src/lua/lvm.c
  bootstrap CC -g ../src/lua/lzio.c
  link lua
  bootstrap CC -g ../src/tup/bin.c
  bootstrap CC -g ../src/tup/colors.c
  bootstrap CC -g ../src/tup/config.c
  bootstrap CC -g ../src/tup/create_name_file.c
  bootstrap CC -g ../src/tup/db.c
  bootstrap CC -g ../src/tup/debug.c
  bootstrap CC -g ../src/tup/delete_name_file.c
  bootstrap CC -g ../src/tup/dircache.c
  bootstrap CC -g ../src/tup/entry.c
  bootstrap CC -g ../src/tup/environ.c
  bootstrap CC -g ../src/tup/estring.c
  bootstrap CC -g ../src/tup/file.c
  bootstrap CC -g ../src/tup/fslurp.c
  bootstrap CC -g ../src/tup/graph.c
  bootstrap CC -g ../src/tup/if_stmt.c
  bootstrap CC -g ../src/tup/init.c
  bootstrap CC -g ../src/tup/lock.c
  bootstrap CC -g ../src/tup/luaparser.c
  bootstrap CC -g ../src/tup/option.c
  bootstrap CC -g ../src/tup/parser.c
  bootstrap CC -g ../src/tup/path.c
  bootstrap CC -g ../src/tup/pel_group.c
  bootstrap CC -g ../src/tup/platform.c
  bootstrap CC -g ../src/tup/privs.c
  bootstrap CC -g ../src/tup/progress.c
  bootstrap CC -g ../src/tup/send_event.c
  bootstrap CC -g ../src/tup/string_tree.c
  bootstrap CC -g ../src/tup/thread_tree.c
  bootstrap CC -g ../src/tup/timespan.c
  bootstrap CC -g ../src/tup/tupid_tree.c
  bootstrap CC -g ../src/tup/updater.c
  bootstrap CC -g ../src/tup/vardb.c
  bootstrap CC -g ../src/tup/vardict.c
  bootstrap CC -g ../src/tup/variant.c
  bootstrap CC -g ../src/tup/varsed.c
  bootstrap CC -g ../src/tup/tup/main.c
  bootstrap CC -g ../src/tup/monitor/null.c
  bootstrap CC -g ../src/tup/flock/fcntl.c
  bootstrap CC -g ../src/tup/server/fuse_fs.c
  bootstrap CC -g ../src/tup/server/fuse_server.c
  bootstrap CC -g ../src/tup/server/master_fork.c
  bootstrap CC -g ../src/inih/ini.c
  bootstrap CC -g ../src/compat/dummy.c
  bootstrap CC -g ../src/compat/clearenv.c
  bootstrap CC -g ../src/sqlite3/sqlite3.c
  bootstrap LD tup -lm
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.122s] Reading in new environment variables...
[ tup ] [0.122s] Parsing Tupfiles...
tup: perfuse_open: setsockopt SO_SNDBUF to 540672 failed: No buffer space available
tup: perfuse_open: setsockopt SO_RCVBUF to 540672 failed: No buffer space available
tup: perfuse_open: setsockopt SO_SNDBUF to 540672 failed: No buffer space available
tup: perfuse_open: setsockopt SO_RCVBUF to 540672 failed: No buffer space available
  1) [0.005s] src/lua
  2) [0.001s] src/luabuiltin
  3) [0.005s] src/tup
  4) [0.001s] src/tup/flock
  5) [0.001s] src/tup/monitor
  6) [0.002s] src/tup/server
  7) [0.001s] src/sqlite3
  8) [0.001s] src/inih
  9) [0.001s] src/compat
 10) [0.001s] src/tup/tup
 11) [0.003s] .
 12) [0.001s] contrib                                                                                                                                                                                                                       
 13) [0.001s] contrib/debian                                                                                                                                                                                                                
 14) [0.001s] contrib/debian/source                                                                                                                                                                                                         
 15) [0.001s] contrib/syntax                                                                                                                                                                                                                
 16) [0.001s] docs                                                                                                                                                                                                                          
 17) [0.001s] docs/html                                                                                                                                                                                                                     
 18) [0.001s] docs/html/pub                                                                                                                                                                                                                 
 19) [0.001s] docs/html/pub/win32                                                                                                                                                                                                           
 20) [0.001s] src                                                                                                                                                                                                                           
 21) [0.001s] src/bsd                                                                                                                                                                                                                       
 22) [0.001s] src/compat/win32                                                                                                                                                                                                              
 23) [0.001s] src/compat/win32/detect                                                                                                                                                                                                       
 24) [0.001s] src/compat/win32/sys                                                                                                                                                                                                          
 25) [0.001s] src/dllinject                                                                                                                                                                                                                 
 26) [0.001s] test                                                                                                                                                                                                                          
 27) [0.001s] test/make_v_tup                                                                                                                                                                                                               
 28) [0.001s] build                                                                                                                                                                                                                         
 29) [0.001s] build/luabuiltin                                                                                                                                                                                                              
 [   ETA~=<1s Remaining=0      ] 100%
[ tup ] [0.166s] No files to delete.                                                                                                                                                                                                        
[ tup ] [0.167s] Generating .gitignore files...
[ tup ] [0.310s] Executing Commands...
 [                           ETA~=??? Remaining=85 Active=8                            ]   0%fuse: writing device: Message too long                                                                                                         
fuse: writing device: Message too long
fuse: writing device: Message too long
fuse: writing device: Message too long
fuse: writing device: Message too long
fuse: writing device: Message too long
fuse: writing device: Message too long
fuse: writing device: Message too long
```

And it hangs forever.

### CODE REVIEW

**Comment by 0joshuaolson1** [comment]
I guess this was abandoned

**Comment by krytarowski** [comment]
We are NetBSD, still alive and not going anywhere.

**Comment by 0joshuaolson1** [comment]
@krytarowski I was referring to this broken 18-month-old PR.

**Comment by krytarowski** [comment]
Why broken?

**Comment by 0joshuaolson1** [comment]
I suppose `src/compat/Tupfile` isn't that big a merge conflict, but there must be some reason why @gittup hasn't acknowledged anything here after all that time.

**Comment by krytarowski** [comment]
This patch is good enough to be merged as is (and perhaps rebased). Before fixing fuse I prefer to get some active feedback and reduction of local patches. I like to work incrementally on NetBSD support.

**Comment by 0joshuaolson1** [comment]
Okay.

**Comment by XVilka** [comment]
@krytarowski is your FUSE also updated the API? In Linux it has changed the API for >=3.0 versions: https://github.com/gittup/tup/issues/402

**Comment by krytarowski** [comment]
@XVilka we can use that fuse library on NetBSD as well. The basesystem one didn't change since my pull-request.

**Comment by gittup** [comment]
Sorry I let this linger so long, but it's finally merged! (Minus the LIST_SWAP macro since it's no longer used in tup.) If the test cases start working, I can add a NetBSD VM to my test infrastructure to ensure they stay working on each commit.

**Comment by krytarowski** [comment]
Thanks!

**Pull request closed without merging**
