### PR TITLE
WIP: Update Lua from 5.2.2 to 5.3.2

### PR DESCRIPTION
**Pull request by anatol**
Here is a list of Lua 5.3 changes http://www.lua.org/manual/5.3/readme.html

### CODE REVIEW

**Comment by gittup** [comment]
Thanks for working on this! Good to see you around again.

What's the reason for adding -DLUA_USE_POSIX? This makes two files fail to compile for me:

*  2) src/lua: MINGWCC ldo.c                                                                                                       
ldo.c: In function 'luaD_rawrunprotected':
ldo.c:67:30: error: too few arguments to function '_setjmp'
 #define LUAI_TRY(L,c,a)  if (_setjmp((c)->b) == 0) { a }
                              ^
ldo.c:142:3: note: in expansion of macro 'LUAI_TRY'
   LUAI_TRY(L, &lj,
   ^
In file included from ldo.c:13:0:
/usr/share/mingw-w64/include/setjmp.h:185:63: note: declared here
   int __cdecl __attribute__ ((__nothrow__,__returns_twice__)) _setjmp(jmp_buf _Buf, void *_Ctx);

* 16) src/lua: MINGWCC lauxlib.c                                                                                                   
lauxlib.c:247:22: fatal error: sys/wait.h: No such file or directory
 #include <sys/wait.h>

When I remove the define, everything compiles successfully and all tests pass. I'm running on Ubuntu 15.10.

**Comment by anatol** [comment]
`LUA_USE_POSIX` is used to define `lua_tmpnam()`. Otherwise compiler complains at Linux.

https://github.com/gittup/tup/pull/282/commits/844700a1f86a6722055dbafcb92729d7625f892d#diff-8f81f7152d255aeb0a17c3a634bf90dbR98

`LUA_USE_POSIX` existed in Lua code in 5.2 and was used to enable other compat defines

```
#define LUA_USE_MKSTEMP
#define LUA_USE_ISATTY
#define LUA_USE_POPEN
#define LUA_USE_ULONGJMP
#define LUA_USE_GMTIME_R
```

But all these `LUA_USE_MKSTEMP`... got removed in 5.3 and it seems we need to use `LUA_USE_POSIX`.


https://github.com/gittup/tup/pull/282/commits/844700a1f86a6722055dbafcb92729d7625f892d#diff-e6bab3f305f922da186c4f86a119d515L68

**Comment by anatol** [comment]
Maybe `-DLUA_USE_POSIX` should be used for Linux (and Macosx?) only?

**Comment by gittup** [comment]
Ahh, somehow I missed that it was MinGW that was failing. I've moved the -DLUA_USE_POSIX inside the !cc rule instead. I also combined the lua import with the patched version into a single commit so that each commit builds & runs tests successfully. I realize there is some information loss there, but the tup_lua.patch file makes up for that I think.

**Comment by anatol** [comment]
And Lua 5.3.3 just got released :)

**Comment by gittup** [comment]
Can't win... :)

**Pull request closed without merging**
