### PR TITLE
Update Lua to 5.4.2 version

### PR DESCRIPTION
**Pull request by data-man**
It's [git-version](https://github.com/lua/lua).
Works for me™.

### CODE REVIEW

**Comment by gittup** [comment]
Thanks for working on this! Where did you grab the lua tarball from? I was just double-checking the tup-lua.patch, and when I compared to https://www.lua.org/ftp/lua-5.4.2.tar.gz (sha1: 96d4a21393c94bed286b8dc0568f4bdde8730b22), I see other differences that look like it came from a different lua version. For example, lapi.c should match the file from the tarball.

**Comment by data-man** [comment]
> Thanks for working on this!

My pleasure! :)

> Where did you grab the lua tarball from?

As I mentioned, this is the git-version from the official repository.
Now updated to https://github.com/lua/lua/commit/c03c527fd207b4ad8f5a8e0f4f2c176bd227c979 commit with a lot of fixes/optimizations.

I can update to the latest release if you prefer it.

**Comment by gittup** [comment]
> > Where did you grab the lua tarball from?
> 
> As I mentioned, this is the git-version from the official repository.

Oops, I missed that in the comment and just saw the 5.4.2 in the commit title. Is there a reason you want to go with the git version rather than a released version?

**Comment by data-man** [comment]
> Is there a reason you want to go with the git version rather than a released version?

I like the optimizations and fixes in Lua made in three months.

**Comment by gittup** [comment]
I'd prefer to stick with released versions rather than git HEAD for now if possible. Any idea when 5.4.3 would be released? We could upgrade to that when it comes out.

**Comment by data-man** [comment]
> I'd prefer to stick with released versions rather than git HEAD for now if possible. 

Ok, pushed. But `tup-lua.patch` can be wrong. :(

> Any idea when 5.4.3 would be released?

No idea.

**Comment by gittup** [comment]
I'm having trouble getting it to pass the test cases. It seems a few things have changed:

1) the tostring override in builtin.lua no longer applies, so t2148 fails to print out the table contents. Maybe we need to override the metatable __tostring somehow?

2) The codename(ls, &key) line in lparser.c gives me this error in a few tests:
`tup error [string "compile.lua"]:3: <name> expected near ''$(GITTUP_ROOT)/<group>''`

3) Removing the above gets a little further, but it seems that tup_append_assignment() isn't called in cases like t2185 where we set 'inputs' to a table, and then try to do 'inputs.extra_inputs += ...' - this fails with:
`tup error [string "compile.lua"]:3: attempt to call a nil value (field 'extra_inputs')`

Oddly, it does go all the way through append_assignment() in lparser.c in the last case.

**Comment by gittup** [comment]
Looks like 5.4.3 was released at the end of March, so I upgraded to that instead. I had the same issues as trying to get the previous version in.

1. For tostring, I decided to no longer try to override it so that `print(table)` will call table.concat automatically. This already didn't work for things like `print("text" .. table)`, where you have to instead do `print("text" .. tostring(table))`, and it seems like it's difficult to get it to work again with the new version (I believe we'd have to provide a default metatable for all tables that defines __tostring, but that feels like it could be problematic).
2. Removing the `codename(ls, &key)` line seems like the correct thing to do with the new API.
3. The tup_append_assignment issue was due to luaK_dischargevars() and freereg() changing in lcode.c. I updated the handling of VINDEXED and added VINDEXI and VINDEXSTR to match the lcode.c paths.

All test cases are passing (with the tostring() change in t2148) and lua-5.4.3 is in master.

**Pull request closed without merging**
