### PR TITLE
Register Lua5.3 packages in the parser

### PR DESCRIPTION
**Pull request by anatol**

### CODE REVIEW

**Comment by Qix-** [comment]
lgtm, though doesn't this introduce some potentially breaking changes to scripts that use the old bitwise library instead of the new utf8 library?

**Comment by anatol** [comment]
The deprecated `bit32` package is unrelated to `utf8`.

`bit32` package has been replaced with explicit bitwise Lua operators. And I am sure that number of people who uses Tup + Lua + bitwise operations is extremely small (if not zero). The risk is too small to justify keeping deprecated lua functionality in Tup.

**Comment by Qix-** [comment]
Fair enough.

**Comment by gittup** [comment]
Merged - thanks for the updates!

**Pull request closed without merging**
