### PR TITLE
Added built-in macro !tup-variant

### PR DESCRIPTION
**Pull request by SquircleSpace**
Input files to !tup-variant are included in variant directories via symlink.

The change was written by Mike and sent out to tup-users.  I found the patch while browsing the archives and thought "Hey!  That's exactly what I need for my project!".

I ran into two issues while applying the patch.
1. The arguments to get_relative_dir have changed since the patch was first written2
2. The context around the last hunk changed quite a bit.  I believe I put it in the proper place.

Seems to work in my project.

### CODE REVIEW

**Comment by ppannuto** [comment]
Could you also update the documentation to explain what this new macro does?

**Comment by bradleyjensen** [comment]
Added some documentation.  I hope I didn't mess up the file -- I'm not especially comfortable with nroff.

**Comment by p2rkw** [comment]
Fixed possible memory leaks: https://github.com/p2rkw/tup/commit/a1781a2d2acf42f56650af68a8b9ca3da38e5bd3

**Comment by gittup** [comment]
Sorry I hadn't merged this! The functionality has since been implemented as !tup_preserve. Let me know if there's a case that this patch handles that doesn't work with !tup_preserve.

**Pull request closed without merging**
