### PR TITLE
Allow generate to run scripts

### LINKED ISSUE #408: `generate` subcommand deadlocks on `run` rule
Hi,

I've been trying to get Tup to generate a build script for a Tupfile involving a `run` command. I.e. running `tup generate build.sh` on:

```
# Tupfile

run ./script.sh
```

where `script.sh` is anything, such as:

```
# script.sh

#!/usr/bin/env sh

printf ''
```

However, it never manages to progress beyond the printing of the command and the environment. Doing a bisect on `tup`, this doesn't seem to have ever worked (at least since the `generate` command existed).

I added loads of print statements everywhere, and the first difference between `tup upd` and `tup generate build.sh` seems to be [`read_all_internal`](https://github.com/gittup/tup/blob/master/src/tup/server/master_fork.c#L325) (Line 325 is the first print label I see).

The main thread is deadlocking on the `pthread_cond_wait` call in [`wait_for_my_sid`](https://github.com/gittup/tup/blob/master/src/tup/server/master_fork.c#L825). I'm not sure how this signal is supposed to be sent, as neither `generate` nor `upd` seems to run the [`master_fork_loop`](https://github.com/gittup/tup/blob/master/src/tup/server/master_fork.c#L719) which is the only place I see the condition being signalled, so not sure how to fix this myself.

### Edit

Adding a `tup_init` call before the `generate` call prevents the deadlocking, however, it stills seems that the environment is not fully configured, as tup errors with:

```
.tup/tmp/output-1: No such file or directory
tup error: Unable to create temporary file for sub-process output.
```

### PR DESCRIPTION
**Pull request by Crystalix007**
Runs the fork server whilst using the generate command. This allows generate sub-command to actually make progress when pushing child commands to the work queue.

Also, added a change to run commands in the resulting build scripts in sub-shells preventing any `cd` commands in rules causing the root directory to change.

Should fix #408.

### CODE REVIEW

**Comment by Crystalix007** [comment]
Also, I would love to sign the CLA, but I think CLAhub's server is down, because it seems like there's no DNS entry for their server right now.

**Comment by gittup** [comment]
Thanks for working on this! I merged the commit to run commands in sub-shells and added a test for it (t2215). I also realized I broke generating a script without 'tup init', so I've fixed that as well.

For getting run-scripts working, I don't think this approach will work. The intention behind 'tup generate' is to allow for doing things like generating pre-built packages in environments that don't allow fuse. (I think it was originally for Debian or Gentoo build environments?) So we'll need a way that doesn't start the dependency server at all.

I think we'll need a way to replace server_run_script() (or maybe a lower method, like exec_internal()?) with one that just does a regular fork/exec instead of using fuse & master_fork. Since we aren't tracking dependencies in the 'tup generate' command, all we really need to do is run the script and get the output.

Hope that makes sense. Let me know if you aren't able to spend more time on it and I can give it a try.

**Comment by gittup** [comment]
Also, thanks for letting me know about CLAhub. I'll have to look into that or find an alternative.

**Comment by Crystalix007** [comment]
I wasn't really sure about where to put the temporary output files used to bind the `run` subprocesses' outputs. Normally, they seem to be placed under `.tup/tmp`, so I also kept them there. The `generate` command seems to not require a `tup init`, so it also creates a `.tup` subdirectory if necessary.

I haven't added any implementation for Windows, since I'm not sure about the syscalls involved.

I've also added a test for this. I *think* the numbering is correct. `t2xxx` is for the `generate` command, right? But if not, feel free to rename as necessary.

**Comment by gittup** [comment]
Thanks for contributing this!

I changed the temporary file implementation in a followup commit. Honestly we could probably get rid of .tup/tmp everywhere and just use tmpfile(), though I think the ldpreload server still needs named temporary files for its dependency storage since we can't always trust the subprocess to pass along open file descriptors.

t2xxx sounds right -- there aren't any hard rules there, but t2xxx is supposed to be for testing things related to the parser, and since run scripts and 'tup generate' all relate to the parser, that seems like a good fit.

Two followup questions:
1) Is there value in having tup with the ldpreload server be able to 'tup generate' a run-script, but not actually be able to run it with tup itself? (Similarly on Windows). I haven't merged your commit for this yet.

2) What are you using run-scripts for? Is there something that the built-in lua parser doesn't support easily?

**Comment by Crystalix007** [comment]
1. This would mainly be useful in a Docker environment, or similar container technology. Since the default way to run Docker images doesn't include the FUSE device, and doesn't have enough permissions to mount it itself, then `ldpreload` is likely the only option for building. Personally, I can work around this for my use case because I intend to just verify `generate` against a build script I push on each commit. But if other use cases have a single Docker image for building Tup projects and generating build scripts, then it might be worth having the ability to generate for Tupfiles with `run` commands, even if they cannot be built directly.

I'm not sure if that's a strong enough case for it though. My original reasoning was just to make it as fully-featured as possible, given that with the fork-exec model, there are no technical reasons why it can't be supported if no dependency tracking is required.

If you feel that the code bloat would be too much / it would be confusing to only support features in `generate` and not `upd`, then I guess I would suggest documentation somewhere about the capabilities of each backend, as it's not very clear what platform should be being used without looking at the code. I assume a lot of people would see the FUSE requirement for the default server and just choose the ldpreload server when using containers, without realising that it doesn't have feature parity for generating build scripts.

2. Honestly, I hadn't checked the Lua parser, given I'm rustier at that than even my C. Also, simply listing file names with some substitution seems easier to do in Bash. No doubt though that Lua would achieve the same goal, but I thought this might end up more complex.

**Comment by gittup** [comment]
I think this was all merged a while back, or at the very least it fixes #408. If I missed anything important here feel free to reopen!

**Pull request closed without merging**
