### PR TITLE
Update SQLite to 3.34

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by gittup** [comment]
Can you update this to the latest master? It's based on a revision that's pretty old.

**Comment by data-man** [comment]
Sorry, I don't know how that happened. :-(

**Comment by gittup** [comment]
No worries - it's merged now, thanks!

**Comment by data-man** [comment]
Lua 5.4.2 is next. It will be more difficult. :-)

**Comment by gittup** [comment]
> Lua 5.4.2 is next. It will be more difficult. :-)

I added a src/lua/tup-lua.patch file to show the differences from lua-5.3.4 when you updated it last time. Hopefully that helps, though I'm not sure how much things have changed in lua itself :)

**Pull request closed without merging**
