### PR TITLE
Update SQLite to 3.37.2

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by gittup** [comment]
Merged - thanks! I used to do this whenever a new version was announced on the sqlite-announce mailing list, but it looks like those were shut down? Did you just happen to see there was a new version or is there some other way I should be notified of those?

**Comment by data-man** [comment]
> Did you just happen to see there was a new version or is there some other way I should be notified of those?

* you can watch the SQLite's [GH mirror](https://github.com/sqlite/sqlite) or
* you can register at [sqlite.org/forum](https://sqlite.org/forum) and change your personal settings:
> Make changes to the email subscription shown below and press "Submit".

Topics: 
- [x] Announcements
- [ ] Check-ins
- [ ] Forum Posts
- [ ] Forum Edits
- [ ] Wiki

**Comment by data-man** [comment]
Also the most popular Linux distributions usually has an up-to-date version of SQLite.
You can check it in https://repology.org/project/sqlite/versions.
Just wondering, what OS are you using? :)

**Comment by gittup** [comment]
> Also the most popular Linux distributions usually has an up-to-date version of SQLite. You can check it in https://repology.org/project/sqlite/versions. Just wondering, what OS are you using? :)

I currently use Ubuntu for my day-to-day stuff, though I have a bunch of VMs to test tup on other distros as well. How about you? :)

**Comment by data-man** [comment]
I currently use Devuan. :)

**Pull request closed without merging**
