### PR TITLE
!tup_preserve macro for including source files into variant builds

### PR DESCRIPTION
**Pull request by zah**
When using in-tree builds, the resulting build outputs may rely on
run-time files placed in the source tree. When using variants, it
may be helpful if such files are included in the variant build dir
as well. This patch provides a new macro "!tup_preserve", which can
be used to achieve this goal:

:foreach *.png |> !tup_preserve |>

Previously discussed here: https://goo.gl/zWsDEo

The patch also fixes the use of !tup_ln with variants.

### CODE REVIEW

**Comment by zah** [comment]
Hi Mike,

I used your tup-variant patch as a starting point, but there were a lot of issues in the update logic, so I decided to take another direction, following the `!tup_ln` implementation. `!tup_ln` had a problem that it didn't try to compute the correct relative paths in variant builds, so I fixed this and arrived at a relatively unified solution for both.

I also tried to use hard links instead of symlinks, but I stumbled into a problem. When a source file gets deleted, its hard-linked copy in the build output directory will appear modified, which triggers the generated -> normal path in `delete_files`. Since symlinks are fine for my project, I didn't dig much deeper into this. The simple refactoring in `do_ln` helped me during my attempts to have an alternative hard-linking function.

All in all, the code have been tested quite a lot and I've added the necessary UX polish and documentation.

**Comment by gittup** [comment]
Thanks for taking this on! Looks pretty good. I have a few comments / questions:

1) Why did you want to change it from !tup_variant to !tup_preserve?
2) This breaks t2188 and t2189, I think because the !tup_ln command changed. Can you take a look?
3) Do you have a simple test case for verify !tup_ln with variants? It would be good to make sure this doesn't break in the future
4) (nitpick) - This patch adds some random newlines. Eg: src/compat/symlinkat.h, src/tup/path.c, and src/tup/parser.c

**Comment by zah** [comment]
Sorry for not running the test suite. I was not familiar with it at the time, but I learned about it during my work on the Windows variants. 

The problem with t2188 and 2189 was just that I added "^ pretty printing^" for both `tup_ln` and `tup_preserve` and this was not followed in the test suite.

tup_variant seemed a little bit arbitrary and ambiguous to me and since other commands are typically verbs, I tried to pick the less ambiguous verb I can think of. Since nobody is supposedly using tup_variant yet, I thought this was an innocent change.

In my last commit, I took the liberty to add an .editorconfig file for the project:
http://editorconfig.org/

Hopefully, this will make it easier for contributors to follow the indentation style of the rest of the code.

**Comment by gittup** [comment]
Thanks for updating it! I did collapse some of the commits and moved the tests around a little bit, but otherwise everything should be intact I believe.

**Pull request closed without merging**
